name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Packer
              uses: hashicorp/setup-packer@v1

            - name: Validate Packer template
              run: packer validate packer/ami.pkr.hcl

            - name: Build Packer image
              run: packer build packer/ami.pkr.hcl

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                  aws-region: eu-west-1

            - name: Initialize Terraform
              run: terraform init infra/

            - name: Validate Terraform
              run: terraform validate infra/

            - name: Apply Terraform
              run: terraform apply -auto-approve infra/