name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                  aws-region: eu-west-1

            - name: Install Packer
              run: |
                curl -L -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
                unzip packer.zip
                sudo mv packer /usr/local/bin/
                packer --version

            - name: Validate Packer template
              run: packer validate Packer/ami.pkr.hcl

            - name: Build Packer image
              run: packer build Packer/ami.pkr.hcl



            - name: Initialize Terraform
              run: terraform init infra/

            - name: Validate Terraform
              run: terraform validate Infra/

            - name: Apply Terraform
              run: terraform apply -auto-approve Isnfra/